[global]
resolution = "{resolution}"
fps = "{fps}"
timecodeFormat = "{timecodeFormat}"
blankLastFrame = true
unitVGapPx = <32>
locale = "{locale}"

[[pageStyle]]
name = "{project.PageBehavior.CARD}"
subsequentGapFrames = {subsequentGapFrames}
behavior = "CARD"
cardRuntimeFrames = {cardRuntimeFrames}
cardFadeInFrames = {cardFadeFrames}
cardFadeOutFrames = {cardFadeFrames}

[[pageStyle]]
name = "{project.PageBehavior.SCROLL}"
subsequentGapFrames = {subsequentGapFrames}
behavior = "SCROLL"
scrollPxPerFrame = {scrollPxPerFrame}

[[contentStyle]]
name = "{project.template.contentStyleHeading}"
bodyLetterStyleName = "{project.template.contentStyleHeading}"
bodyLayout = "GRID"

[[contentStyle]]
name = "{project.template.contentStyleSubheading}"
bodyLetterStyleName = "{project.template.letterStyleSmall}"
bodyLayout = "GRID"

[[contentStyle]]
name = "{project.template.contentStyleGutter}"
blockOrientation = "HORIZONTAL"
spineAttachment = "HEAD_GAP_CENTER"
bodyLetterStyleName = "{project.template.letterStyleName}"
bodyLayout = "GRID"
gridMatchColWidths = "ACROSS_BLOCKS"
gridCellHJustifyPerCol = ["LEFT"]
hasHead = true
headLetterStyleName = "{project.template.letterStyleSmall}"
headMatchWidth = "ACROSS_BLOCKS"
headHJustify = "RIGHT"
headVJustify = "TOP"
headGapPx = <24>

[[contentStyle]]
name = "{project.template.contentStyleBullets}"
bodyLetterStyleName = "{project.template.letterStyleName}"
bodyLayout = "FLOW"
flowLineWidthPx = <800>
flowHGapPx = <32>
hasHead = true
headLetterStyleName = "{project.template.letterStyleSmall}"
headGapPx = <4>

[[contentStyle]]
name = "{project.template.contentStyleTabular}"
bodyLetterStyleName = "{project.template.letterStyleName}"
bodyLayout = "GRID"
gridStructure = "EQUAL_WIDTH_COLS"
gridCellHJustifyPerCol = ["LEFT", "CENTER", "RIGHT"]
gridColGapPx = <32>

[[contentStyle]]
name = "{project.template.contentStyleSong}"
bodyLetterStyleName = "{project.template.letterStyleSmall}"
bodyLayout = "GRID"
hasHead = true
headLetterStyleName = "{project.template.letterStyleSongTitle}"
headGapPx = 0.0

[[contentStyle]]
name = "{project.template.contentStyleLogos}"
bodyLetterStyleName = "{project.template.letterStyleNormal}"
bodyLayout = "FLOW"
flowLineWidthPx = <1200>
flowLineGapPx = <64>
flowHGapPx = <96>
flowSeparator = ""

[[contentStyle]]
name = "{project.template.contentStyleBlurb}"
bodyLetterStyleName = "{project.template.letterStyleNormal}"
bodyLayout = "PARAGRAPHS"
paragraphsLineWidthPx = <500>
paragraphsParaGapPx = <8>

[[contentStyle]]
name = "{project.PageBehavior.CARD}"
bodyLetterStyleName = "{project.template.letterStyleCardName}"
bodyLayout = "GRID"
hasHead = true
headLetterStyleName = "{project.template.letterStyleCardSmall}"
headGapPx = <32>
hasTail = true
tailLetterStyleName = "{project.template.letterStyleCardSmall}"
tailGapPx = <32>

[[letterStyle]]
name = "{project.template.letterStyleNormal}"
fontName = "Archivo Narrow Regular"
heightPx = <32>

[[letterStyle]]
name = "{project.template.letterStyleSmall}"
fontName = "Archivo Narrow Regular"
heightPx = <24>

[[letterStyle]]
name = "{project.template.contentStyleHeading}"
fontName = "Archivo Narrow Regular"
heightPx = <32>
trackingEm = 0.05

[[letterStyle.layers]]
name = "{project.LayerShape.TEXT}"
shape = "TEXT"

[[letterStyle.layers]]
name = "{project.StripePreset.UNDERLINE}"
shape = "STRIPE"
stripePreset = "UNDERLINE"

[[letterStyle]]
name = "{project.template.letterStyleName}"
fontName = "Archivo Narrow Bold"
heightPx = <32>

[[letterStyle]]
name = "{project.template.letterStyleSongTitle}"
fontName = "Archivo Narrow Bold"
heightPx = <32>
smallCaps = "SMALL_CAPS"

[[letterStyle]]
name = "{project.template.letterStyleCardName}"
fontName = "Archivo Narrow Bold"
heightPx = <100>

[[letterStyle]]
name = "{project.template.letterStyleCardSmall}"
fontName = "Archivo Narrow Regular"
heightPx = <50>

[[pictureStyle]]
name = "Cinecred H"
picture = "Cinecred H.svg"
heightPx = <90>
cropBlankSpace = true

[[pictureStyle]]
name = "Cinecred V"
picture = "Cinecred V.svg"
heightPx = <150>
cropBlankSpace = true
